### ISSUE TITLE
Gary Bernhardt's talk video

### ISSUE THREAD

**Issue by ggarnier** [strangeloop/StrangeLoop2015#23]
I checked the [videos](https://www.youtube.com/playlist?list=PLcGKfGEEONaCIl5eU53uPBnRJ9rbIH32R) from StangeLoop 2015, but I can't find Gary Bernhardt's talk.

**Comment by puredanger** [comment]
Gary asked for his talk not to be released as he was going to present it more times. Feel free to contact him about it.

**Comment by ggarnier** [comment]
:+1:

Did he release the slides?

**Comment by puredanger** [comment]
No
